In [5]:
import pandas as pd
import numpy as np
import xlrd as xl
import openpyxl as px

In [6]:
Energy = pd.read_excel('Energy Indicators.xls',header=None,skipfooter=0)

Energy = Energy.drop([0,1],axis=1)
Energy = Energy.dropna()

Energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

Energy = Energy.drop([9],axis=0)

Energy["Country"] = Energy["Country"].replace({r"[0-9\"]+":""},regex=True)
Energy["Country"] = Energy["Country"].replace({r'\s*\([^)]*\)':""},regex=True)

Energy["Country"] = Energy["Country"].replace({"Republic of Korea": "South Korea", "United States of America": "United States", "United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "China, Hong Kong Special Administrative Region": "Hong Kong"})

Energy["Energy Supply"] = Energy["Energy Supply"]*1000000

In [7]:
GDP = pd.read_csv('world_bank.csv',skiprows=5,header=None,skipfooter=0)

GDP[0] = GDP[0].replace({"Korea, Rep.": "South Korea", "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"})

GDP[GDP[0]== "South Korea"] 

#continua hasta 48
GDP.drop(range(1, 50), axis=1, inplace=True)

In [8]:
Energy = pd.read_excel('Energy Indicators.xls',header=None,skipfooter=0)

Energy = Energy.drop([0,1],axis=1)
Energy = Energy.dropna()

Energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

Energy = Energy.drop([9],axis=0)

Energy["Country"] = Energy["Country"].replace({r"[0-9\"]+":""},regex=True)
Energy["Country"] = Energy["Country"].replace({r'\s*\([^)]*\)':""},regex=True)

Energy["Country"] = Energy["Country"].replace({"Republic of Korea": "South Korea", "United States of America": "United States", "United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "China, Hong Kong Special Administrative Region": "Hong Kong"})

Energy["Energy Supply"] = Energy["Energy Supply"]*1000000

GDP = pd.read_csv('world_bank.csv',skiprows=5,header=None,skipfooter=0)

GDP[0] = GDP[0].replace({"Korea, Rep.": "South Korea", "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"})

GDP[GDP[0]== "South Korea"] 

#continua hasta 48
GDP.drop(range(1, 50), axis=1, inplace=True)

ScimEn = pd.read_excel('scimagojr-3.xlsx')
ScimEn

df = pd.merge(ScimEn,Energy,how='inner',left_on='Country',right_on='Country')

df = pd.merge(df,GDP,how='inner',left_on='Country',right_on=0)
df.drop([0],axis=1,inplace=True)
df = df.set_index('Country')

df.columns = ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']

mask = df['Rank'] <= 15

df = df[mask]
df

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,127191000000,93,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,90838000000,286,11.57098,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,18984000000,149,10.23282,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920000000,124,10.60047,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709000000,214,17.28868,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,10431000000,296,61.94543,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,13261000000,165,17.90153,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,33195000000,26,14.96908,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,10597000000,166,17.02028,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,11007000000,221,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6530000000,109,33.66723,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4923000000,106,37.96859,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9172000000,119,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5386000000,231,11.81081,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,12149000000,59,69.64803,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [9]:
avgGDP = df.groupby("Country", as_index=True)[['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']].mean().mean(axis=1).sort_values(ascending=False)
avgGDP
type(avgGDP)

pandas.core.series.Series

In [10]:
avgGDP
df

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,127191000000,93,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,90838000000,286,11.57098,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,18984000000,149,10.23282,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920000000,124,10.60047,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709000000,214,17.28868,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,10431000000,296,61.94543,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,13261000000,165,17.90153,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,33195000000,26,14.96908,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,10597000000,166,17.02028,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,11007000000,221,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6530000000,109,33.66723,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4923000000,106,37.96859,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9172000000,119,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5386000000,231,11.81081,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,12149000000,59,69.64803,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [11]:
sext = "United Kingdom"

cambio = df.loc[sext]['2015'] - df.loc[sext]['2006']

In [12]:
por = df.sort_values(by='% Renewable',ascending=False)
tupla = (por.index[0],por.iloc[0]['% Renewable'])

In [13]:
suply = df["Energy Supply per Capita"].mean()

In [14]:
df["ratio"] = df["Self-citations"]/df["Citations"]
final = df.sort_values(by="ratio",ascending=False)
tupla = (final.iloc[0].name,final.iloc[0].ratio)
tupla

('China', 0.6893126179389422)

In [15]:
df["population"] = df["Energy Supply"]/df["Energy Supply per Capita"]

pop = df

pop.sort_values(by="population",ascending=False,inplace=True)

type(pop.iloc[2].name)

str

In [16]:
median = df["% Renewable"].median()

def fun1(num):
    if num >= median:
        return 1
    else:
        return 0

df["Por encima"] = df["% Renewable"].apply(fun1)

sort = df.sort_values(by="Por encima",ascending=True)

sort["Por encima"]

Country
India                 0
United States         0
Japan                 0
Iran                  0
United Kingdom        0
South Korea           0
Australia             0
China                 1
Brazil                1
Russian Federation    1
Germany               1
France                1
Italy                 1
Spain                 1
Canada                1
Name: Por encima, dtype: int64

In [17]:
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}

nuevo = df["population"]
nuevo_df = pd.DataFrame(nuevo)

nuevo_df.reset_index
nuevo_df['Continent'] = nuevo_df.index.map(ContinentDict)

nuevo_df.set_index('Continent')
final = nuevo_df.groupby('Continent',as_index=True).agg(['size', 'sum', 'mean', 'std'])
final.columns = final.columns.droplevel(0)
final

               size               sum              mean           std
Continent
Asia              5   2898666386.6106   579733277.32212  6.790979e+08
Australia         1   23316017.316017   23316017.316017           NaN
Europe            6  457929667.216372   76321611.202729  3.464767e+07
North America     2   352855249.48025  176427624.740125  1.996696e+08
South America     1  205915254.237288  205915254.237288           NaN

In [18]:
pi.shape[1]

NameError: name 'pi' is not defined

In [ ]:
df['% Renewable bins'] = pd.cut(df['% Renewable'], 5)
result = df.groupby(['Continent', '% Renewable bins']).size().dropna()
len(result)

/tmp/ipykernel_8166/2655232211.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result = df.groupby(['Continent', '% Renewable bins']).size().dropna()

25

In [ ]:
df

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2011,2012,2013,2014,2015,ratio,population,Por encima,Continent,% Renewable bins
Country,,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,127191000000,93,19.75491,...,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,1367645161.290323,1,Asia,"(15.753, 29.227]"
India,8,15005,14841,128763,37209,8.58,115,33195000000,26,14.96908,...,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,1276730769.230769,0,Asia,"(2.212, 15.753]"
United States,2,96661,94747,792274,265436,8.20,230,90838000000,286,11.57098,...,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0.335031,317615384.615385,0,North America,"(2.212, 15.753]"
Brazil,15,8668,8596,60702,14396,7.00,86,12149000000,59,69.64803,...,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,0.237159,205915254.237288,1,South America,"(56.174, 69.648]"
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709000000,214,17.28868,...,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0.362517,143500000.0,1,Europe,"(15.753, 29.227]"
Japan,3,30504,30287,223024,61554,7.31,134,18984000000,149,10.23282,...,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0.275997,127409395.973154,0,Asia,"(2.212, 15.753]"
Germany,7,17027,16831,140566,27426,8.26,126,13261000000,165,17.90153,...,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,0.195111,80369696.969697,1,Europe,"(15.753, 29.227]"
Iran,13,8896,8819,57470,19125,6.46,72,9172000000,119,5.707721,...,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0.332782,77075630.252101,0,Asia,"(2.212, 15.753]"
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920000000,124,10.60047,...,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0.183773,63870967.741935,0,Europe,"(2.212, 15.753]"
France,9,13153,12973,130632,28601,9.93,114,10597000000,166,17.02028,...,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,0.218943,63837349.39759,1,Europe,"(15.753, 29.227]"
Italy,11,10964,10794,111850,26661,10.20,106,6530000000,109,33.66723,...,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,0.238364,59908256.880734,1,Europe,"(29.227, 42.701]"
South Korea,10,11983,11923,114675,22595,9.57,104,11007000000,221,2.279353,...,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,0.197035,49805429.864253,0,Asia,"(2.212, 15.753]"
Spain,12,9428,9330,123336,23964,13.08,115,4923000000,106,37.96859,...,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,0.194299,46443396.226415,1,Europe,"(29.227, 42.701]"
Canada,6,17899,17620,215003,40930,12.01,149,10431000000,296,61.94543,...,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,0.190369,35239864.864865,1,North America,"(56.174, 69.648]"
Australia,14,8831,8725,90765,15606,10.28,107,5386000000,231,11.81081,...,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0.171939,23316017.316017,0,Australia,"(2.212, 15.753]"

In [ ]:


df['PopEst'] = df['population'].apply(lambda x: '{:,}'.format(x))

In [ ]:
def answer_three():
    Energy = pd.read_excel('assets/Energy Indicators.xls',header=None,skipfooter=0)

    Energy = Energy.drop([0,1],axis=1)
    Energy = Energy.dropna()

    Energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

    Energy = Energy.drop([9],axis=0)

    Energy["Country"] = Energy["Country"].replace({r"[0-9\"]+":""},regex=True)
    Energy["Country"] = Energy["Country"].replace({r'\s*\([^)]*\)':""},regex=True)
    
    Energy["Country"] = Energy["Country"].replace({"Republic of Korea": "South Korea", "United States of America": "United States", "United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "China, Hong Kong Special Administrative Region": "Hong Kong"})
    
    Energy["Energy Supply"] = Energy["Energy Supply"]*1000000
    
    GDP = pd.read_csv('assets/world_bank.csv',skiprows=5,header=None,skipfooter=0)
    
    GDP[0] = GDP[0].replace({"Korea, Rep.": "South Korea", "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"})
    
    GDP[GDP[0]== "South Korea"] 
    
    #continua hasta 48
    GDP.drop(range(1, 50), axis=1, inplace=True)
    
    ScimEn = pd.read_excel('assets/scimagojr-3.xlsx')
    ScimEn
    
    df = pd.merge(ScimEn,Energy,how='inner',left_on='Country',right_on='Country')
    
    df = pd.merge(df,GDP,how='inner',left_on='Country',right_on=0)
    df.drop([0],axis=1,inplace=True)
    df = df.set_index('Country')
    
    df.columns = ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
    
    mask = df['Rank'] <= 15
    mask2 = df['Rank'] > 15
    
    df1 = df[mask]
    
    df2 = df[mask2]
    
    return len(df2)
    raise NotImplementedError()

In [ ]:
def answer_twelve():
    Energy = pd.read_excel('Energy Indicators.xls',header=None,skipfooter=0)

    Energy = Energy.drop([0,1],axis=1)
    Energy = Energy.dropna()

    Energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

    Energy = Energy.drop([9],axis=0)

    Energy["Country"] = Energy["Country"].replace({r"[0-9\"]+":""},regex=True)
    Energy["Country"] = Energy["Country"].replace({r'\s*\([^)]*\)':""},regex=True)
    
    Energy["Country"] = Energy["Country"].replace({"Republic of Korea": "South Korea", "United States of America": "United States", "United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "China, Hong Kong Special Administrative Region": "Hong Kong"})
    
    Energy["Energy Supply"] = Energy["Energy Supply"]*1000000
    
    GDP = pd.read_csv('world_bank.csv',skiprows=5,header=None,skipfooter=0)
    
    GDP[0] = GDP[0].replace({"Korea, Rep.": "South Korea", "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"})
    
    GDP[GDP[0]== "South Korea"] 
    
    #continua hasta 48
    GDP.drop(range(1, 50), axis=1, inplace=True)
    
    ScimEn = pd.read_excel('scimagojr-3.xlsx')
    ScimEn
    
    df = pd.merge(ScimEn,Energy,how='inner',left_on='Country',right_on='Country')
    
    df = pd.merge(df,GDP,how='inner',left_on='Country',right_on=0)
    df.drop([0],axis=1,inplace=True)
    df = df.set_index('Country')    
    df.columns = ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']   
    mask = df['Rank'] <= 15
    df = df[mask]
    
    ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}


    df['Continent'] = df.index.map(ContinentDict)
    
    df["population"] = df["Energy Supply"]/df["Energy Supply per Capita"]
    
    # Especifica los bins manualmente
    bins = [0, 20, 40, 60, 80, 100]
    df['% Renewable'] = pd.cut(df['% Renewable'], bins)
    
    # Asegúrate de que estás agrupando por las columnas correctas
    result = df.groupby(['Continent', '% Renewable']).filter(lambda x: len(x) > 0).groupby(['Continent', '% Renewable']).count()['Rank']

    def remove_zero(val):
        if val == 0:
            return None
        else:
            return val


    result = result.apply(remove_zero)

    result = result.dropna()
    
    return result

answer_twelve()

/tmp/ipykernel_4795/354791948.py:65: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result = df.groupby(['Continent', '% Renewable']).filter(lambda x: len(x) > 0).groupby(['Continent', '% Renewable']).count()['Rank']
/tmp/ipykernel_4795/354791948.py:65: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result = df.groupby(['Continent', '% Renewable']).filter(lambda x: len(x) > 0).groupby(['Continent', '% Renewable']).count()['Rank']

Continent      % Renewable
Asia           (0, 20]        5.0
Australia      (0, 20]        1.0
Europe         (0, 20]        4.0
               (20, 40]       2.0
North America  (0, 20]        1.0
               (60, 80]       1.0
South America  (60, 80]       1.0
Name: Rank, dtype: float64

In [ ]:
import statistics as stats

df
df["population"] = df["Energy Supply"]/df["Energy Supply per Capita"]
df["Energy Supply per Capita"] = pd.to_numeric(df["Energy Supply per Capita"], errors='coerce')
df["estimates the number of citable documents per person"] = (df["Citable documents"]/df["population"]).dropna()
df

df["estimates the number of citable documents per person"].corr(df["Energy Supply per Capita"])

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2010,2011,2012,2013,2014,2015,ratio,population,Por encima,estimates the number of citable documents per person
Country,,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,127191000000,93,19.75491,...,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,1367645161.290323,1,0.000093
India,8,15005,14841,128763,37209,8.58,115,33195000000,26,14.96908,...,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,1276730769.230769,0,0.000012
United States,2,96661,94747,792274,265436,8.20,230,90838000000,286,11.57098,...,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0.335031,317615384.615385,0,0.000298
Brazil,15,8668,8596,60702,14396,7.00,86,12149000000,59,69.64803,...,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,0.237159,205915254.237288,1,0.000042
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709000000,214,17.28868,...,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0.362517,143500000.0,1,0.000128
Japan,3,30504,30287,223024,61554,7.31,134,18984000000,149,10.23282,...,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0.275997,127409395.973154,0,0.000238
Germany,7,17027,16831,140566,27426,8.26,126,13261000000,165,17.90153,...,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,0.195111,80369696.969697,1,0.000209
Iran,13,8896,8819,57470,19125,6.46,72,9172000000,119,5.707721,...,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0.332782,77075630.252101,0,0.000114
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920000000,124,10.60047,...,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0.183773,63870967.741935,0,0.000319
France,9,13153,12973,130632,28601,9.93,114,10597000000,166,17.02028,...,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,0.218943,63837349.39759,1,0.000203
Italy,11,10964,10794,111850,26661,10.20,106,6530000000,109,33.66723,...,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,0.238364,59908256.880734,1,0.00018
South Korea,10,11983,11923,114675,22595,9.57,104,11007000000,221,2.279353,...,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,0.197035,49805429.864253,0,0.000239
Spain,12,9428,9330,123336,23964,13.08,115,4923000000,106,37.96859,...,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,0.194299,46443396.226415,1,0.000201
Canada,6,17899,17620,215003,40930,12.01,149,10431000000,296,61.94543,...,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,0.190369,35239864.864865,1,0.0005
Australia,14,8831,8725,90765,15606,10.28,107,5386000000,231,11.81081,...,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0.171939,23316017.316017,0,0.000374

In [ ]:
import statistics as stats
def answer_nine():

    
    Energy = pd.read_excel('Energy Indicators.xls',header=None,skipfooter=0)

    Energy = Energy.drop([0,1],axis=1)
    Energy = Energy.dropna()

    Energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

    Energy = Energy.drop([9],axis=0)

    Energy["Country"] = Energy["Country"].replace({r"[0-9\"]+":""},regex=True)
    Energy["Country"] = Energy["Country"].replace({r'\s*\([^)]*\)':""},regex=True)
    
    Energy["Country"] = Energy["Country"].replace({"Republic of Korea": "South Korea", "United States of America": "United States", "United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "China, Hong Kong Special Administrative Region": "Hong Kong"})
    
    Energy["Energy Supply"] = Energy["Energy Supply"]*1000000
    
    GDP = pd.read_csv('world_bank.csv',skiprows=5,header=None,skipfooter=0)
    
    GDP[0] = GDP[0].replace({"Korea, Rep.": "South Korea", "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"})
    
    GDP[GDP[0]== "South Korea"] 
    
    #continua hasta 48
    GDP.drop(range(1, 50), axis=1, inplace=True)
    
    ScimEn = pd.read_excel('scimagojr-3.xlsx')
    ScimEn
    
    df = pd.merge(ScimEn,Energy,how='inner',left_on='Country',right_on='Country')
    
    df = pd.merge(df,GDP,how='inner',left_on='Country',right_on=0)
    df.drop([0],axis=1,inplace=True)
    df = df.set_index('Country')    
    df.columns = ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']   
    mask = df['Rank'] <= 15
    df = df[mask]
    
    
    df["population"] = df["Energy Supply"]/df["Energy Supply per Capita"]
    
   
    df["citable documents per capita and the energy supply per capita"] = df["Citable documents"]/df["population"]

    return df["citable documents per capita and the energy supply per capita"].corr(df["Energy Supply per Capita"])
    
    raise NotImplementedError()
print(answer_nine())

0.7940010435442942

In [22]:
import statistics as stats
import pandas as pd
def answer_nine():

    
    Energy = pd.read_excel('Energy Indicators.xls',header=None,skipfooter=0)

    Energy = Energy.drop([0,1],axis=1)
    Energy = Energy.dropna()

    Energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

    Energy = Energy.drop([9],axis=0)

    Energy["Country"] = Energy["Country"].replace({r"[0-9\"]+":""},regex=True)
    Energy["Country"] = Energy["Country"].replace({r'\s*\([^)]*\)':""},regex=True)
    
    Energy["Country"] = Energy["Country"].replace({"Republic of Korea": "South Korea", "United States of America": "United States", "United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "China, Hong Kong Special Administrative Region": "Hong Kong"})
    
    Energy["Energy Supply"] = Energy["Energy Supply"]*1000000
    
    GDP = pd.read_csv('world_bank.csv',skiprows=5,header=None,skipfooter=0)
    
    GDP[0] = GDP[0].replace({"Korea, Rep.": "South Korea", "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"})
    
    GDP[GDP[0]== "South Korea"] 
    
    #continua hasta 48
    GDP.drop(range(1, 50), axis=1, inplace=True)
    
    ScimEn = pd.read_excel('scimagojr-3.xlsx')
    ScimEn
    
    df = pd.merge(ScimEn,Energy,how='inner',left_on='Country',right_on='Country')
    
    df = pd.merge(df,GDP,how='inner',left_on='Country',right_on=0)
    df.drop([0],axis=1,inplace=True)
    df = df.set_index('Country')    
    df.columns = ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']   
    mask = df['Rank'] <= 15
    df = df[mask]
    
    
    df["population"] = df["Energy Supply"]/df["Energy Supply per Capita"]
    
   
    df["citable documents per capita"] = df["Citable documents"]/df["population"]

    return df["citable documents per capita"].corr(df["Energy Supply per Capita"])
    
    raise NotImplementedError()
print(answer_nine())

0.7940010435442942

In [23]:
df["population"] = df["Energy Supply"]/df["Energy Supply per Capita"]
    
   
df["citable documents per capita"] = df["Citable documents"]/df["population"]
df

df["citable documents per capita"].corr(df["Energy Supply per Capita"])

0.7940010435442945

In [24]:

def answer_nine():
    Energy = pd.read_excel('assets/Energy Indicators.xls',header=None,skipfooter=0)

    Energy = Energy.drop([0,1],axis=1)
    Energy = Energy.dropna()

    Energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

    Energy = Energy.drop([9],axis=0)

    Energy["Country"] = Energy["Country"].replace({r"[0-9\"]+":""},regex=True)
    Energy["Country"] = Energy["Country"].replace({r'\s*\([^)]*\)':""},regex=True)
    
    Energy["Country"] = Energy["Country"].replace({"Republic of Korea": "South Korea", "United States of America": "United States", "United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "China, Hong Kong Special Administrative Region": "Hong Kong"})
    
    Energy["Energy Supply"] = Energy["Energy Supply"]*1000000
    
    GDP = pd.read_csv('assets/world_bank.csv',skiprows=5,header=None,skipfooter=0)
    
    GDP[0] = GDP[0].replace({"Korea, Rep.": "South Korea", "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"})
    
    GDP[GDP[0]== "South Korea"] 
    
    #continua hasta 48
    GDP.drop(range(1, 50), axis=1, inplace=True)
    
    ScimEn = pd.read_excel('assets/scimagojr-3.xlsx')
    ScimEn
    
    df = pd.merge(ScimEn,Energy,how='inner',left_on='Country',right_on='Country')
    
    df = pd.merge(df,GDP,how='inner',left_on='Country',right_on=0)
    df.drop([0],axis=1,inplace=True)
    df = df.set_index('Country')    
    df.columns = ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']   
    mask = df['Rank'] <= 15
    df = df[mask]
    
    
    df["population"] = df["Energy Supply"]/df["Energy Supply per Capita"]
    
   
    df["citable documents per capita"] = df["Citable documents"]/df["population"]

    return df["citable documents per capita"].corr(df["Energy Supply per Capita"])

print(answer_nine())

FileNotFoundError: [Errno 2] No such file or directory: 'assets/Energy Indicators.xls'

In [27]:
def answer_ten():
    Energy = pd.read_excel('Energy Indicators.xls',header=None,skipfooter=0)

    Energy = Energy.drop([0,1],axis=1)
    Energy = Energy.dropna()

    Energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

    Energy = Energy.drop([9],axis=0)

    Energy["Country"] = Energy["Country"].replace({r"[0-9\"]+":""},regex=True)
    Energy["Country"] = Energy["Country"].replace({r'\s*\([^)]*\)':""},regex=True)
    
    Energy["Country"] = Energy["Country"].replace({"Republic of Korea": "South Korea", "United States of America": "United States", "United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "China, Hong Kong Special Administrative Region": "Hong Kong"})
    
    Energy["Energy Supply"] = Energy["Energy Supply"]*1000000
    
    GDP = pd.read_csv('world_bank.csv',skiprows=5,header=None,skipfooter=0)
    
    GDP[0] = GDP[0].replace({"Korea, Rep.": "South Korea", "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"})
    
    GDP[GDP[0]== "South Korea"] 
    
    #continua hasta 48
    GDP.drop(range(1, 50), axis=1, inplace=True)
    
    ScimEn = pd.read_excel('scimagojr-3.xlsx')
    ScimEn
    
    df = pd.merge(ScimEn,Energy,how='inner',left_on='Country',right_on='Country')
    
    df = pd.merge(df,GDP,how='inner',left_on='Country',right_on=0)
    df.drop([0],axis=1,inplace=True)
    df = df.set_index('Country')    
    df.columns = ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']   
    mask = df['Rank'] <= 15
    df = df[mask]
    
    
    
    
    
    
    median = df["% Renewable"].median()

    def fun1(num):
        if num >= median:
            return 1
        else:
            return 0

    df["Por encima"] = df["% Renewable"].apply(fun1)

    
    HighRenew = df.sort_values(by="Rank",ascending=True)
    return HighRenew["Por encima"]
    raise NotImplementedError()
    
    
    
    
print(answer_ten())

Country
China                 1
United States         0
Japan                 0
United Kingdom        0
Russian Federation    1
Canada                1
Germany               1
India                 0
France                1
South Korea           0
Italy                 1
Spain                 1
Iran                  0
Australia             0
Brazil                1
Name: Por encima, dtype: int64

In [28]:
df

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2011,2012,2013,2014,2015,ratio,population,Por encima,citable documents per capita,citable documents per capita
Country,,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,127191000000,93,19.75491,...,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,1367645161.290323,1,0.000093,0.000093
India,8,15005,14841,128763,37209,8.58,115,33195000000,26,14.96908,...,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,1276730769.230769,0,0.000012,0.000012
United States,2,96661,94747,792274,265436,8.20,230,90838000000,286,11.57098,...,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0.335031,317615384.615385,0,0.000298,0.000298
Brazil,15,8668,8596,60702,14396,7.00,86,12149000000,59,69.64803,...,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,0.237159,205915254.237288,1,0.000042,0.000042
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709000000,214,17.28868,...,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0.362517,143500000.0,1,0.000128,0.000128
Japan,3,30504,30287,223024,61554,7.31,134,18984000000,149,10.23282,...,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0.275997,127409395.973154,0,0.000238,0.000238
Germany,7,17027,16831,140566,27426,8.26,126,13261000000,165,17.90153,...,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,0.195111,80369696.969697,1,0.000209,0.000209
Iran,13,8896,8819,57470,19125,6.46,72,9172000000,119,5.707721,...,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0.332782,77075630.252101,0,0.000114,0.000114
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920000000,124,10.60047,...,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0.183773,63870967.741935,0,0.000319,0.000319
France,9,13153,12973,130632,28601,9.93,114,10597000000,166,17.02028,...,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,0.218943,63837349.39759,1,0.000203,0.000203
Italy,11,10964,10794,111850,26661,10.20,106,6530000000,109,33.66723,...,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,0.238364,59908256.880734,1,0.00018,0.00018
South Korea,10,11983,11923,114675,22595,9.57,104,11007000000,221,2.279353,...,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,0.197035,49805429.864253,0,0.000239,0.000239
Spain,12,9428,9330,123336,23964,13.08,115,4923000000,106,37.96859,...,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,0.194299,46443396.226415,1,0.000201,0.000201
Canada,6,17899,17620,215003,40930,12.01,149,10431000000,296,61.94543,...,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,0.190369,35239864.864865,1,0.0005,0.0005
Australia,14,8831,8725,90765,15606,10.28,107,5386000000,231,11.81081,...,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0.171939,23316017.316017,0,0.000374,0.000374