In [419]:
import pandas as pd
import numpy as np

In [420]:
df_1958 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/1958_presidencia_dta_b207497adf.csv")
df_1962 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/1962_presidencia_dta_01961baa15.csv")
df_1966 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/1966_presidencia_dta_0d32570383.csv")
df_1970 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/1970_presidencia_dta_4ad395caa0.csv")
df_1974 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/1974_presidencia_dta_d22d6ad0ab.csv")
df_1978 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/1978_presidencia_dta_b26a4ec76e.csv")
df_1982 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/1982_presidencia_dta_8370cde398.csv")
df_1986 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/1986_presidencia_dta_a73548c70c.csv")
df_1990 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/1990_presidencia_dta_3ed0dd871b.csv")
df_1994 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/1994_presidencia_primera_vuelta_dta_93f7b5c96a.csv")
df_1998 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/1998_presidencia_primera_vuelta_dta_e2a3b897bf.csv")
df_2002 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/2002_presidencia_dta_c5a0392d8f.csv")
df_2006 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/2006_presidencia_dta_9eb2e9319c.csv")
df_2010 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/2010_presidencia_primera_vuelta_dta_b3dfcb91d9.csv")
df_2014 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/2014_presidencia_primera_vuelta_dta_5cf9e9fded.csv")
df_2018 = pd.read_csv("/home/ptro/Code/un/TLP/Curso/code/Presidencial/elecciones/2018_presidencia_primera_vuelta_dta_a61a1a0633.csv")

df_final = pd.concat([df_1958,df_1962,df_1966,df_1970,df_1974,df_1978,df_1982,df_1986,df_1990,df_1994,df_1998,df_2002,df_2006,df_2010,df_2014,df_2018])




df_partidos = df_final[["codigo_partido","votos"]]

np.sum(df_partidos["votos"])
df_final = df_final.replace({18480001:"Partido liberal",20020001:"Primero Colombia",18490002:"Partido conservador",20130001:"Centro democratico",20050002:"Partido de la U",20180001:"Partido verde"})

df_final.set_index(["departamento","municipio"],inplace=True)

In [421]:
final = pd.DataFrame()
a = pd.DataFrame()
dic = {}

lista_partido = []
lista_votos = []
for group, frame in df_final.groupby("codigo_partido"):
    votos = np.sum(frame["votos"])
    lista_partido.append(group)
    lista_votos.append(votos)

In [422]:
df = pd.DataFrame(list(zip(lista_partido, lista_votos)),
               columns =['id_partido', 'Votos'])
df.sort_values(by=["Votos"],ascending=False)

             id_partido     Votos
73      Partido liberal  32314324
75     Primero Colombia  13260490
71  Partido conservador  12839528
70   Centro democratico  11386119
72      Partido de la U  10112837
..                  ...       ...
0            19589999.0       267
18           19860001.0       229
16           19829999.0       159
4            19709999.0        11
8            19749999.0         6

[76 rows x 2 columns]

In [423]:
df_final[df_final["codigo_partido"]==18480001][["nombres","primer_apellido"]] #### Partido liberal

df_final[df_final["codigo_partido"]==20020001][["nombres","primer_apellido"]] #### Primero colombia (El de Uribe)

df_final[df_final["codigo_partido"]==18490002][["nombres","primer_apellido"]] ## Partido conservador

df_final[df_final["codigo_partido"]==20130001][["nombres","primer_apellido","segundo_apellido"]] ## Centro democratico

df_final[df_final["codigo_partido"]==20050002][["nombres","primer_apellido","segundo_apellido"]] ## Partido de la U (Santos)
df_repalce = df.replace({18480001:"Partido liberal",20020001:"Primero colombia (El de Uribe)",18490002:"Partido conservador",20130001:"Centro democratico",20050002:"Partido de la U (Santos)"})
df_repalce.sort_values(by="Votos",ascending=False)

             id_partido     Votos
73      Partido liberal  32314324
75     Primero Colombia  13260490
71  Partido conservador  12839528
70   Centro democratico  11386119
72      Partido de la U  10112837
..                  ...       ...
0            19589999.0       267
18           19860001.0       229
16           19829999.0       159
4            19709999.0        11
8            19749999.0         6

[76 rows x 2 columns]

In [424]:

lista_apellido = []
lista_votos_apellido = []
for group, frame in df_final.groupby("primer_apellido"):
    votos = np.sum(frame["votos"])
    lista_apellido.append(group)
    lista_votos_apellido.append(votos)

df = pd.DataFrame(list(zip(lista_apellido, lista_votos_apellido)),
               columns =['Primer_apellido', 'Votos'])
df.sort_values(by=["Votos"],ascending=False)

   Primer_apellido     Votos
77           URIBE  13260490
69          SANTOS  10112837
70           SERPA   8601446
54        PASTRANA   7866395
41           LOPEZ   7685864
..             ...       ...
32       GOYENECHE       595
56           PEREZ       229
60          PORRAS       159
2           ARENAS        14
12        CORREDOR        11

[84 rows x 2 columns]

In [425]:
df_final[df_final["primer_apellido"]=="LOPEZ"]["nombres"].unique()

array(['ALFONSO', 'CLARA EUGENIA'], dtype=object)

In [426]:
df_final

                        id_electoral   ano tipo_eleccion fecha_eleccion  \
departamento municipio
ANTIOQUIA    MEDELLIN      119580001  1958   Presidencia       Marzo 16
             MEDELLIN      119580001  1958   Presidencia       Marzo 16
             MEDELLIN      119580001  1958   Presidencia       Marzo 16
             MEDELLIN      119580001  1958   Presidencia       Marzo 16
             MEDELLIN      119580001  1958   Presidencia       Marzo 16
...                              ...   ...           ...            ...
VICHADA      CUMARIBO      120180001  2018   Presidencia        Mayo 27
             CUMARIBO      120180001  2018   Presidencia        Mayo 27
             CUMARIBO      120180001  2018   Presidencia        Mayo 27
             CUMARIBO      120180001  2018   Presidencia        Mayo 27
             CUMARIBO      120180001  2018   Presidencia        Mayo 27

                        coddpto58  coddpto departamento58  codmpio58  codmpio  \
departamento municipio
ANTIOQUIA    MEDELLIN         5.0      5.0      ANTIOQUIA     5001.0   5001.0
             MEDELLIN         5.0      5.0      ANTIOQUIA     5001.0   5001.0
             MEDELLIN         5.0      5.0      ANTIOQUIA     5001.0   5001.0
             MEDELLIN         5.0      5.0      ANTIOQUIA     5001.0   5001.0
             MEDELLIN         5.0      5.0      ANTIOQUIA     5001.0   5001.0
...                           ...      ...            ...        ...      ...
VICHADA      CUMARIBO         NaN     99.0            NaN        NaN  99773.0
             CUMARIBO         NaN     99.0            NaN        NaN  99773.0
             CUMARIBO         NaN     99.0            NaN        NaN  99773.0
             CUMARIBO         NaN     99.0            NaN        NaN  99773.0
             CUMARIBO         NaN     99.0            NaN        NaN  99773.0

                       circunscripcion  ... codmpio82  coddpto86  \
departamento municipio                  ...
ANTIOQUIA    MEDELLIN         Nacional  ...       NaN        NaN
             MEDELLIN         Nacional  ...       NaN        NaN
             MEDELLIN         Nacional  ...       NaN        NaN
             MEDELLIN         Nacional  ...       NaN        NaN
             MEDELLIN         Nacional  ...       NaN        NaN
...                                ...  ...       ...        ...
VICHADA      CUMARIBO         Nacional  ...       NaN        NaN
             CUMARIBO         Nacional  ...       NaN        NaN
             CUMARIBO         Nacional  ...       NaN        NaN
             CUMARIBO         Nacional  ...       NaN        NaN
             CUMARIBO         Nacional  ...       NaN        NaN

                       departamento86 codmpio86 coddpto90  departamento90  \
departamento municipio
ANTIOQUIA    MEDELLIN             NaN       NaN       NaN             NaN
             MEDELLIN             NaN       NaN       NaN             NaN
             MEDELLIN             NaN       NaN       NaN             NaN
             MEDELLIN             NaN       NaN       NaN             NaN
             MEDELLIN             NaN       NaN       NaN             NaN
...                               ...       ...       ...             ...
VICHADA      CUMARIBO             NaN       NaN       NaN             NaN
             CUMARIBO             NaN       NaN       NaN             NaN
             CUMARIBO             NaN       NaN       NaN             NaN
             CUMARIBO             NaN       NaN       NaN             NaN
             CUMARIBO             NaN       NaN       NaN             NaN

                        codmpio90  coddpto94 departamento94  codmpio94
departamento municipio
ANTIOQUIA    MEDELLIN         NaN        NaN            NaN        NaN
             MEDELLIN         NaN        NaN            NaN        NaN
             MEDELLIN         NaN        NaN            NaN        NaN
             MEDELLIN         NaN        NaN            NaN        NaN
             MEDELLIN         NaN        NaN            NaN        NaN
...                           ...        ...            ...        ...
VICHADA      CUMARIBO         NaN        NaN            NaN        NaN
             CUMARIBO         NaN        NaN            NaN        NaN
             CUMARIBO         NaN        NaN            NaN        NaN
             CUMARIBO         NaN        NaN            NaN        NaN
             CUMARIBO         NaN        NaN            NaN        NaN

[175438 rows x 44 columns]

In [427]:


union = df_final.loc["ANTIOQUIA","LA UNION"]

/tmp/ipykernel_56825/2585585993.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  union = df_final.loc["ANTIOQUIA","LA UNION"]

In [428]:
union = df_final.loc["ANTIOQUIA","LA UNION"]
union.columns
union = union.drop(columns=['coddpto58',
       'coddpto', 'departamento58', 'codmpio58', 'codmpio', 'circunscripcion', 'codigo_lista'])

union = union.drop(columns=['coddpto62', 'departamento62',
       'codmpio62', 'coddpto66', 'departamento66', 'codmpio66', 'coddpto70',
       'departamento70', 'codmpio70', 'coddpto74', 'departamento74',
       'codmpio74', 'coddpto78', 'departamento78', 'codmpio78', 'coddpto82',
       'departamento82', 'codmpio82', 'coddpto86', 'departamento86',
       'codmpio86', 'coddpto90', 'departamento90', 'codmpio90', 'coddpto94',
       'departamento94', 'codmpio94'])
union
union[union["ano"]==2018]

/tmp/ipykernel_56825/2073072013.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  union = df_final.loc["ANTIOQUIA","LA UNION"]

                        id_electoral   ano tipo_eleccion fecha_eleccion  \
departamento municipio
ANTIOQUIA    LA UNION      120180001  2018   Presidencia        Mayo 27
             LA UNION      120180001  2018   Presidencia        Mayo 27
             LA UNION      120180001  2018   Presidencia        Mayo 27
             LA UNION      120180001  2018   Presidencia        Mayo 27
             LA UNION      120180001  2018   Presidencia        Mayo 27
             LA UNION      120180001  2018   Presidencia        Mayo 27
             LA UNION      120180001  2018   Presidencia        Mayo 27
             LA UNION      120180001  2018   Presidencia        Mayo 27
             LA UNION      120180001  2018   Presidencia        Mayo 27
             LA UNION      120180001  2018   Presidencia        Mayo 27
             LA UNION      120180001  2018   Presidencia        Mayo 27

                            codigo_partido       primer_apellido  \
departamento municipio
ANTIOQUIA    LA UNION           20180003.0                 PETRO
             LA UNION           20180004.0                   NaN
             LA UNION   Centro democratico                 DUQUE
             LA UNION           20180002.0           DE LA CALLE
             LA UNION           20170002.0              TRUJILLO
             LA UNION        Partido verde               FAJARDO
             LA UNION           20180005.0               MORALES
             LA UNION           20180006.0                VARGAS
             LA UNION                  NaN  TARJETAS NO MARCADAS
             LA UNION                  NaN           VOTOS NULOS
             LA UNION                  NaN       VOTOS EN BLANCO

                       segundo_apellido                    nombres  votos  \
departamento municipio
ANTIOQUIA    LA UNION            URREGO          GUSTAVO FRANCISCO    488
             LA UNION               NaN  PROMOTORES VOTO EN BLANCO     18
             LA UNION           MARQUEZ                       IVAN   6167
             LA UNION           LOMBANA                   HUMBERTO    167
             LA UNION         SARMIENTO              JORGE ANTONIO     24
             LA UNION        VALDERRAMA                     SERGIO   3650
             LA UNION             HOYOS             VIVIANE ALEIDA     21
             LA UNION            LLERAS                     GERMAN    403
             LA UNION               NaN                        NaN     41
             LA UNION               NaN                        NaN    122
             LA UNION               NaN                        NaN    133

                        curules
departamento municipio
ANTIOQUIA    LA UNION         1
             LA UNION         0
             LA UNION         1
             LA UNION         0
             LA UNION         0
             LA UNION         0
             LA UNION         0
             LA UNION         0
             LA UNION         0
             LA UNION         0
             LA UNION         0

In [429]:
lista_partido = []
lista_votos = []
for group, frame in union.groupby("codigo_partido"):
    votos = np.sum(frame["votos"])
    lista_partido.append(group)
    lista_votos.append(votos)

df = pd.DataFrame(list(zip(lista_partido, lista_votos)),
               columns =['id_partido', 'Votos'])
df.sort_values(by=["Votos"],ascending=False)

             id_partido  Votos
73      Partido liberal  14939
70   Centro democratico   9651
75     Primero Colombia   7879
71  Partido conservador   7180
72      Partido de la U   5588
..                  ...    ...
8            19749999.0      0
4            19709999.0      0
3            19669999.0      0
2            19629999.0      0
0            19589999.0      0

[76 rows x 2 columns]

In [430]:
union.to_csv("Elecciones_Presidenciales_LaUnion_1958-2018.csv")

In [431]:
antioquia = df_final.loc["ANTIOQUIA"]
antioquia_conservador = antioquia[antioquia["codigo_partido"]=="Partido conservador"]
antioquia_conservador

,id_electoral,ano,tipo_eleccion,fecha_eleccion,coddpto58,coddpto,departamento58,codmpio58,codmpio,circunscripcion,...,codmpio82,coddpto86,departamento86,codmpio86,coddpto90,departamento90,codmpio90,coddpto94,departamento94,codmpio94
municipio,,,,,,,,,,,,,,,,,,,,,
MEDELLIN,119580001,1958,Presidencia,Marzo 16,5.0,5.0,ANTIOQUIA,5001.0,5001.0,Nacional,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABEJORRAL,119580001,1958,Presidencia,Marzo 16,5.0,5.0,ANTIOQUIA,5002.0,5002.0,Nacional,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABRIAQUI,119580001,1958,Presidencia,Marzo 16,5.0,5.0,ANTIOQUIA,5004.0,5004.0,Nacional,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ALEJANDRIA,119580001,1958,Presidencia,Marzo 16,5.0,5.0,ANTIOQUIA,5021.0,5021.0,Nacional,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AMAGA,119580001,1958,Presidencia,Marzo 16,5.0,5.0,ANTIOQUIA,5030.0,5030.0,Nacional,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YALI,120140001,2014,Presidencia,Mayo 25,NaN,5.0,NaN,NaN,5885.0,Nacional,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YARUMAL,120140001,2014,Presidencia,Mayo 25,NaN,5.0,NaN,NaN,5887.0,Nacional,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YOLOMBO,120140001,2014,Presidencia,Mayo 25,NaN,5.0,NaN,NaN,5890.0,Nacional,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YONDO,120140001,2014,Presidencia,Mayo 25,NaN,5.0,NaN,NaN,5893.0,Nacional,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZARAGOZA,120140001,2014,Presidencia,Mayo 25,NaN,5.0,NaN,NaN,5895.0,Nacional,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [432]:
lista_municipio = []
lista_votos = []
for group, frame in antioquia_conservador.groupby("municipio"):
    votos = np.sum(frame["votos"])
    lista_municipio.append(group)
    lista_votos.append(votos)

votos_conservador = pd.DataFrame(list(zip(lista_municipio, lista_votos)),
               columns =['Municipio', 'Votos_conservador'])
votos_conservador.sort_values(by=["Votos_conservador"],ascending=False)

             Municipio  Votos_conservador
72            MEDELLIN             597958
16               BELLO              82826
61              ITAGUI              65721
49            ENVIGADO              62816
113             SONSON              27569
..                 ...                ...
92          SAN ANDRES                637
74             MURINDO                530
67          LA PINTADA                414
98   SAN JUAN DE URABA                221
127   VIGIA DEL FUERTE                181

[133 rows x 2 columns]

In [433]:
lista_municipio = []
lista_votos = []
for group, frame in antioquia.groupby("municipio"):
    votos = np.sum(frame["votos"])
    lista_municipio.append(group)
    lista_votos.append(votos)

votos_antioquia= pd.DataFrame(list(zip(lista_municipio, lista_votos)),
               columns =['Municipio', 'Votos_totales'])
votos_antioquia.sort_values(by=["Votos_totales"],ascending=False)

                      Municipio  Votos_totales
72                     MEDELLIN        5988134
16                        BELLO         977612
49                     ENVIGADO         808719
61                       ITAGUI         775314
90                     RIONEGRO         368845
..                          ...            ...
74                      MURINDO           6944
94                   SAN ANDRES           5371
85   PUERTO NARE (LA MAGDALENA)           3914
112        SANTAFE DE ANTIOQUIA           3607
86               PUERTO TRIFUNO           1634

[136 rows x 2 columns]

In [434]:
porcentaje = pd.merge(votos_antioquia,votos_conservador,how="right")
porcentaje

      Municipio  Votos_totales  Votos_conservador
0     ABEJORRAL          73512              14427
1      ABRIAQUI          10237               2393
2    ALEJANDRIA          19258               3575
3         AMAGA          84125               9423
4        AMALFI          46641               5693
..          ...            ...                ...
128        YALI          21680               2804
129     YARUMAL         119437              21677
130     YOLOMBO          55608               9081
131       YONDO          29737                913
132    ZARAGOZA          48225               5145

[133 rows x 3 columns]

In [435]:
porcentaje
porcentaje.loc["Porcentaje_votos_conservador"] = 0

In [436]:
for i, row in porcentaje.iterrows():
    if row["Votos_totales"] != 0:
        porcentaje_total = (row["Votos_conservador"] / row["Votos_totales"]) * 100
        porcentaje.loc[i, "Porcentaje_votos_conservador"] = porcentaje_total
    else:
        porcentaje.loc[i, "Porcentaje_votos_conservador"] = "Indefinido"
porcentaje
porcentaje.replace({"Indefinido":0},inplace=True)
porcentaje

/tmp/ipykernel_56825/772026132.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Indefinido' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  porcentaje.loc[i, "Porcentaje_votos_conservador"] = "Indefinido"

,Municipio,Votos_totales,Votos_conservador,Porcentaje_votos_conservador
0,ABEJORRAL,73512,14427,19.625367
1,ABRIAQUI,10237,2393,23.375989
2,ALEJANDRIA,19258,3575,18.563714
3,AMAGA,84125,9423,11.201189
4,AMALFI,46641,5693,12.205999
...,...,...,...,...
129,YARUMAL,119437,21677,18.149317
130,YOLOMBO,55608,9081,16.330384
131,YONDO,29737,913,3.070249
132,ZARAGOZA,48225,5145,10.668740
Porcentaje_votos_conservador,0,0,0,0.000000

In [437]:
porcentaje.sort_values(by="Porcentaje_votos_conservador",ascending=False)

,Municipio,Votos_totales,Votos_conservador,Porcentaje_votos_conservador
111,SANTUARIO,21378,9211,43.086350
55,GRANADA,61046,20971,34.352783
93,SAN ANDRES DE CUERQUIA,14568,4459,30.608182
94,SAN CARLOS,68037,19318,28.393374
37,COCORNA,75082,20687,27.552543
...,...,...,...,...
102,SAN PEDRO DE URABA,52097,1047,2.009713
78,NECOCLI,62368,1088,1.744484
127,VIGIA DEL FUERTE,11541,181,1.568322
98,SAN JUAN DE URABA,29345,221,0.753110
Porcentaje_votos_conservador,0,0,0,0.000000

In [453]:

antioquia_verde = antioquia[antioquia["codigo_partido"]=="Partido verde"]
lista_municipio = []
lista_votos = []
for group, frame in antioquia_verde.groupby("municipio"):
    votos = np.sum(frame["votos"])
    lista_municipio.append(group)
    lista_votos.append(votos)

votos_verde = pd.DataFrame(list(zip(lista_municipio, lista_votos)),
               columns =['Municipio', 'Votos_verde'])
votos_verde.sort_values(by=["Votos_verde"],ascending=False)


porcentaje = pd.merge(porcentaje,votos_verde)

porcentaje.loc["Porcentaje_votos_verde"] = 0

for i, row in porcentaje.iterrows():
    if row["Votos_totales"] != 0:
        porcentaje_total = (row["Votos_verde"] / row["Votos_totales"]) * 100
        porcentaje.loc[i, "Porcentaje_votos_verde"] = porcentaje_total
    else:
        porcentaje.loc[i, "Porcentaje_votos_verde"] = "Indefinido"
porcentaje.replace({"Indefinido":0},inplace=True)

porcentaje.sort_values(by="Porcentaje_votos_verde",ascending=False)

/tmp/ipykernel_56825/887353222.py:23: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Indefinido' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  porcentaje.loc[i, "Porcentaje_votos_verde"] = "Indefinido"

,Municipio,Votos_totales,Votos_conservador,Porcentaje_votos_conservador,Votos_verde,Porcentaje_votos_verde
86,SABANETA,176734,14163,8.013738,15047,8.513925
49,GIRARDOTA,132829,16956,12.765285,10791,8.123979
62,LA ESTRELLA,156829,15325,9.771790,12424,7.922004
23,CALDAS,213418,18480,8.659063,15928,7.463288
42,EL CARMEN DE VIBORAL,116067,15418,13.283707,8120,6.995959
...,...,...,...,...,...,...
11,ARBOLETES,82354,6598,8.011754,670,0.813561
13,ARMENIA,24103,3272,13.575074,193,0.800730
72,NARINO,41912,10603,25.298244,223,0.532067
12,ARGELIA,30542,7143,23.387466,134,0.438740
Porcentaje_votos_verde,0,0,0,0.000000,0,0.000000

In [457]:
porcentaje.to_csv("porcentaje.csv")